apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: scaleway-secret-sync
  namespace: kube-system
spec:
  destination:
    create: true
    name: scaleway-csi-secrets
  hmacSecretData: true
  mount: secret
  path: k8s/kube-system/scaleway-csi-secrets
  type: kv-v2
  vaultAuthRef: kube-system-vault-auth