apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: PODINFO_UI_MESSAGE
        value: "Served by ${HOSTNAME} from node ${NODE_NAME}"