apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command: ["/bin/sh","-c"]
          args:
            - >
              exec /podinfo
              --port=9898
              --ui-message="Served by ${HOSTNAME} from node ${NODE_NAME}"
