apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  namespace: dns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hcloud-volumes
