apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: platform
spec:
  secretName: vault-server-tls
  issuerRef:
    kind: Issuer
    name: vault-internal-ca-issuer
  commonName: hashicorp-vault.platform.svc
  dnsNames:
    # Service names
    - hashicorp-vault.platform.svc
    - hashicorp-vault.platform.svc.cluster.local
    - "*.platform.svc"
    - "*.platform.svc.cluster.local"
    # Pod DNS names for Raft peers
    - hashicorp-vault-0.hashicorp-vault-internal
    - hashicorp-vault-1.hashicorp-vault-internal
    - hashicorp-vault-2.hashicorp-vault-internal
  ipAddresses:
    - 127.0.0.1
  usages:
    - digital signature
    - key encipherment
    - server auth
